<?php
/**
 * Created by PhpStorm.
 * User: merloot
 * Date: 09.03.20
 * Time: 20:15
 */

namespace frontend\models;


use common\models\User;
use yii\base\Model;

class CodeForm extends Model {

    public $code;
    public function rules()
    {
        return [

        ];
    }

    public function validate($attributeNames = null, $clearErrors = true) {
        return parent::validate($attributeNames, $clearErrors); // TODO: Change the autogenerated stub
    }

    public function run(){
        $user = User::findOne();
        $user->code = $this->code;
        if ($user->update()){
            return true;
        }
        return false;
    }
}